class data_base():

    def position_avaliable() -> list:
        
        data_base_positive = [
            "Ótimo curso!",
            "Excelente conteúdo e instrutor.",
            "Aprendizado incrível!",
            "Recomendo fortemente.",
            "Muito satisfeito com o curso.",
            "Conteúdo de alta qualidade.",
            "Instrutor experiente e bem preparado.",
            "Melhor curso que já fiz.",
            "Amei cada minuto do curso.",
            "Material didático excelente.",
            "Conteúdo atualizado e relevante.",
            "Didática clara e objetiva.",
            "Suporte e atendimento ao aluno de primeira.",
            "Um curso que realmente faz a diferença.",
            "Superou minhas expectativas.",
            "Apliquei o que aprendi imediatamente no meu trabalho.",
            "Curso indispensável para quem deseja aprender programação.",
            "Excelente custo-benefício.",
            "Conteúdo bem estruturado e organizado.",
            "Materiais complementares enriquecedores.",
            "Curso altamente recomendado.",
            "Excelente plataforma de aprendizado online.",
            "Aprendi muito e me senti motivado durante todo o curso.",
            "Clareza nas explicações e exemplos práticos.",
            "Conteúdo abrangente e bem explicado.",
            "Um dos melhores cursos da área.",
            "Fácil de acompanhar e entender.",
            "Avaliação máxima para esse curso!", 
            "Adorei este vídeo! Muito informativo e bem explicado.",
            "Esse conteúdo é incrível! Aprendi muito com esse vídeo.",
            "Que vídeo maravilhoso! Sempre quis saber sobre esse assunto.",
            "Estou impressionado com a qualidade deste vídeo. Ótimo trabalho!",
            "Excelente explicação. Continuem com o bom trabalho!",
            "Esse canal sempre entrega conteúdos de alto nível. Gostei muito!",
            "Muito obrigado por compartilhar conhecimento tão valioso.",
            "Esse vídeo merece mil likes. Compartilhando com todos!",
            "Simplesmente fantástico! Não vejo a hora de assistir ao próximo.",
            "A maneira como esse assunto foi abordado torna tudo mais fácil de entender.", 
            "Apreciei muito a forma clara como os conceitos foram apresentados.",
            "Fiquei realmente impressionado com a qualidade das animações neste vídeo.",
            "Parabéns aos criadores por mais um conteúdo enriquecedor.",
            "Esse é definitivamente um dos melhores canais para aprender sobre este tema.",
            "Admiro a dedicação da equipe em fornecer informações precisas e atualizadas.",
            "Sem dúvida, vou voltar a assistir este vídeo sempre que precisar revisar.",
            "As dicas compartilhadas aqui são extremamente úteis. Muito obrigado!",
            "Estou surpreso com o quão envolvente esse vídeo é. Nem percebi o tempo passar.",
            "Gostaria de ver mais vídeos colaborativos como este. A combinação de ideias é genial.",
            "Que achado este canal! Recomendarei a todos os meus amigos.",
            "A paixão do apresentador pelo assunto é contagiante. Continuem assim!",
            "A simplicidade da explicação torna tudo acessível até para iniciantes.",
            "Já estou ansioso pelo próximo vídeo. Mal posso esperar para aprender mais.",
            "A qualidade do áudio e vídeo faz toda a diferença na minha experiência.",
            "Essa abordagem prática realmente me ajuda a entender e reter as informações.",
            "Uma verdadeira aula disfarçada de vídeo online. Muito bem elaborado.",
            "Esse canal conseguiu tornar um tópico complexo em algo fácil de absorver.",
            "Amei a energia positiva que o apresentador transmite. Isso faz toda a diferença.",
            "Estou me sentindo mais confiante sobre esse assunto graças a este vídeo.",
            "Os exemplos reais apresentados enriquecem bastante o entendimento.",
            "Uau, simplesmente uau! Este vídeo superou minhas expectativas.",
            "Compartilhando isso imediatamente. Todos precisam ver este conteúdo incrível.",
            "Estou tão grato por ter encontrado este canal. Está me ajudando muito.",
            "Este é o tipo de vídeo que me inspira a aprender e explorar mais.",
            "A maneira descontraída como o apresentador ensina torna tudo mais agradável.",
            "Os gráficos e ilustrações são muito bem feitos. Facilitam muito a compreensão.",
            "Mal posso acreditar que esse conteúdo é gratuito. É de altíssima qualidade.",
            "Não entendo como este canal ainda não tem milhões de inscritos. Merece!",
            "Assistir a este vídeo foi um uso produtivo do meu tempo. Aprendi muito.",
            "Essas informações são tão valiosas que eu pagaria para tê-las. Sorte a minha que é de graça!",
            "O esforço e a pesquisa dedicados a este vídeo são evidentes. Parabéns!",
            "Este vídeo é um verdadeiro tesouro de conhecimento. Obrigado por compartilhar.",
            "Agradeço por tornar tópicos complexos em algo acessível para todos nós.",
            "As metáforas usadas tornam a compreensão mais fácil. Um excelente trabalho!",
            "Nunca imaginei que pudesse entender esse assunto até assistir a este vídeo.",
            "Estou recomendando este canal a todos os colegas de trabalho. Vale muito a pena.",
            "Este vídeo está me motivando a explorar mais a fundo esse tópico por conta própria.",
            "Não vou mais perder tempo procurando informações. Este canal é meu novo guia.",
            "Cada vez que assisto a um vídeo aqui, minha mente se expande um pouco mais.",
            "O conteúdo é apresentado de forma tão envolvente que não consigo parar de assistir.",
            "Estou impressionado com o nível de pesquisa que foi colocado neste vídeo. Excelente!",
            "É tão bom ver alguém tão apaixonado por compartilhar conhecimento. Isso é inspirador.",
            "Esse é o tipo de vídeo que eu gostaria de ter assistido quando estava na escola.",
            "Achei que seria difícil acompanhar, mas o apresentador tornou tudo muito simples.",
            "Agradeço por transformar um tópico desafiador em algo que posso entender facilmente.",
            "Já me inscrevi no canal e ativei as notificações. Não quero perder nenhum conteúdo.",
            "O trabalho que foi colocado na pesquisa e na preparação deste vídeo é evidente. Parabéns!",
            "Este é um daqueles raros vídeos que conseguem ser educativos e divertidos ao mesmo tempo.",
            "Estou compartilhando este vídeo com minha rede social. Todos deveriam ter acesso a isso.",
            "Estou realmente surpreso com a profundidade deste vídeo. Abordou todos os ângulos possíveis.",
            "A explicação é tão clara que estou me sentindo como um especialista no assunto agora!",
            "Estou encantado com a qualidade das informações fornecidas neste vídeo. Muito obrigado!",
            "O exemplo prático apresentado tornou tudo muito mais tangível. Ótima abordagem.",
            "Cada minuto deste vídeo é recheado de valor. Não há desperdício de tempo.",
            "Estou tão grato por encontrar um recurso tão valioso para aprimorar meu conhecimento.",
            "Assistir a este vídeo me fez perceber o quanto ainda tenho a aprender. E estou empolgado com isso!",
            "A maneira como o apresentador articula as ideias torna o conteúdo ainda mais cativante.",
            "Nunca pensei que diria isso sobre um vídeo educacional, mas estou ansioso pelo próximo!",
            "As analogias usadas tornam"]

        return data_base_positive

    def negative_avaliable() -> list:
       
        data_base_negative = [
            "Péssimo curso!",
            "Conteúdo fraco e mal explicado.",
            "Não recomendo.",
            "Muito insatisfeito com o curso.",
            "Material didático de baixa qualidade.",
            "Instrutor pouco preparado.",
            "Pior curso que já fiz.",
            "Detestei cada minuto do curso.",
            "Conteúdo desatualizado e irrelevante.",
            "Didática confusa e pouco objetiva.",
            "Suporte e atendimento ao aluno inexistentes.",
            "Um curso que não cumpre o prometido.",
            "Ficou aquém das minhas expectativas.",
            "Não consegui aplicar o que aprendi no meu trabalho.",
            "Curso dispensável para quem deseja aprender programação.",
            "Preço elevado para a qualidade oferecida.",
            "Conteúdo mal estruturado e desorganizado.",
            "Materiais complementares sem valor agregado.",
            "Curso não recomendado.",
            "Plataforma de aprendizado online problemática.",
            "Não aprendi nada de útil durante o curso.",
            "Explicações confusas e exemplos mal elaborados.",
            "Conteúdo superficial e mal explicado.",
            "Um dos piores cursos da área.",
            "Difícil de acompanhar e entender.",
            "Avaliação mínima para esse curso!",
            "Que perda de tempo assistir a este vídeo. Não aprendi nada.",
            "Esse conteúdo é terrível. Não consegui acompanhar as explicações.",
            "O apresentador parece completamente perdido. Não dá para entender nada.",
            "Esperava muito mais deste vídeo, mas fiquei profundamente decepcionado.",
            "O canal costumava ser bom, mas a qualidade caiu muito com este vídeo.",
            "Não recomendaria este vídeo nem ao meu pior inimigo. É péssimo.",
            "Não consegui nem assistir até o final. A qualidade é horrível.",
            "Fico me perguntando como alguém pode fazer um vídeo tão ruim assim.",
            "Se pudesse dar zero estrelas, eu daria. Absolutamente detestável.",
            "Pior vídeo que já vi. Não entendi nada e me sinto mais confuso agora.",
            "Não sei como alguém pode gostar disso. É um desperdício total.",
            "Essa foi uma experiência frustrante. O conteúdo não faz sentido algum.",
            "A qualidade do áudio e do vídeo é tão ruim que mal consegui escutar.",
            "Não há coerência neste vídeo. Parece que as informações foram jogadas aleatoriamente.",
            "Estou irritado por ter perdido tempo assistindo a isso. Não vale a pena.",
            "O apresentador não tem ideia do que está falando. Fiquei totalmente perdido.",
            "Não recomendo nem para meu pior inimigo. É simplesmente insuportável.",
            "Este vídeo conseguiu me deixar mais confuso do que eu estava antes.",
            "É impressionante como alguém pode produzir algo tão ruim. Total falta de esforço.",
            "Até tentei dar uma chance, mas não dá para suportar mais de alguns minutos.",
            "Não entendi qual era o objetivo deste vídeo. Parece que foi feito às pressas.",
            "Que conteúdo desastroso. Não consegui absorver nada do que foi dito.",
            "Nunca me senti tão frustrado assistindo a um vídeo. Total perda de tempo.",
            "Parece que o apresentador nem se preparou. É como se estivesse improvisando o tempo todo.",
            "Não consegui chegar nem à metade do vídeo. É muito ruim para aguentar.",
            "O título prometia muito mais do que o vídeo entregou. Total decepção.",
            "Não me sinto mais esclarecido depois de assistir a isso. Só mais confuso.",
            "Estou me perguntando como alguém pode dar positivo a este vídeo. É um mistério.",
            "Que desastre absoluto. Não acredito que perdi tempo com isso.",
            "O conteúdo é tão fraco que nem sei por onde começar a criticar.",
            "Nada neste vídeo faz sentido. É como se estivessem falando em outra língua.",
            "Não recomendaria nem mesmo para alguém que quisesse perder tempo.",
            "Sinto como se meu cérebro estivesse derretendo depois de assistir a isso.",
            "Esse é o tipo de vídeo que me faz pensar em desistir de aprender sobre o assunto.",
            "Não sei como esse vídeo foi publicado. É um completo desastre.",
            "Não consegui encontrar um único ponto positivo neste vídeo. É terrível.",
            "O apresentador parece entediado e isso se reflete na qualidade do conteúdo.",
            "Parece que não houve nenhuma pesquisa ou preparação para este vídeo.",
            "Fiquei frustrado com a falta de clareza e estrutura deste conteúdo.",
            "Não sei como alguém pode aprender alguma coisa com este vídeo confuso.",
            "A narração monótona torna o vídeo ainda mais difícil de acompanhar.",
            "Estou chocado com a falta de qualidade deste vídeo. É inacreditável.",
            "O pior é que não posso recuperar o tempo que perdi assistindo a isso.",
            "Não há sequer um momento de interesse neste vídeo. É tudo chato e confuso.",
            "Não entendi qual era o objetivo deste vídeo. É uma bagunça completa.",
            "Não consigo acreditar que alguém deu luz verde para a publicação deste lixo.",
            "É triste ver um canal que já foi bom produzindo conteúdo tão horrível.",
            "O apresentador parece tão desinteressado quanto eu estou assistindo a isso.",
            "Não consigo encontrar nenhum ponto positivo neste vídeo. É simplesmente ruim.",
            "Sinto que perdi uma parte do meu cérebro assistindo a isso. Que desastre.",
            "Até tentei acompanhar, mas o conteúdo é tão incoerente que desisti.",
            "Este é um exemplo perfeito de como não fazer um vídeo educacional.",
            "É um milagre que tenha assistido até o fim. A qualidade é péssima.",
            "Esperava algo muito melhor do que isso. É uma verdadeira decepção.",
            "Estou me perguntando como esse vídeo foi aprovado para publicação.",
            "A confusão deste vídeo me deixou mais perplexo do que quando comecei.",
            "O apresentador parece completamente desconectado do assunto. Não faz sentido.",
            "Não recomendaria este vídeo nem mesmo para meu pior inimigo. É insuportável.",
            "Não sei como alguém pode dar positivo a isso. É o pior conteúdo que já vi.",
            "Não entendi nada. É como se as informações estivessem embaralhadas.",
            "É doloroso assistir a alguém tentando explicar algo sem saber do que está falando.",
            "Que desperdício de tempo. Fico me perguntando por que perdi tempo com isso.",
            "Nunca vi algo tão ruim quanto este vídeo. Não há nenhum valor aqui.",
            "A qualidade deste vídeo é tão baixa que meus olhos doem de assistir.",
            "O apresentador parece estar lendo um roteiro pela primeira vez. Total falta de fluência.",
            "Estou genuinamente irritado por ter perdido tempo com este conteúdo.",
            "Não acredito que continuei assistindo a isso esperando que melhorasse. Foi em vão.",
            "É quase como se o apresentador estivesse tentando me confundir de propósito.",
            "Assistir a este vídeo foi uma experiência extremamente frustrante. Não recomendo.",
            "Estou impressionado com o quanto esse vídeo é ruim em todos os aspectos.",
            "Parece que este vídeo foi feito sem qualquer cuidado ou planejamento.",
        ]
        
        return data_base_negative
    