# Use a imagem base oficial do Python
FROM python:3.10-slim-buster

# Define o diretório de trabalho dentro do container
WORKDIR /app

RUN apt-get update \
    && apt-get install -y gcc python3-dev \
    && pip install --upgrade pip \
    && rm -rf /var/lib/apt/lists/*

# Copia os requisitos do projeto e instala as dependências
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copia o código fonte da API para o diretório de trabalho
COPY . .

# Expõe a porta que a API FastAPI está rodando
EXPOSE 4000

# Comando para iniciar a API quando o container for executado
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4000"]
